language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "TrmCIyeC7cFSp42N9iAlxXP5BNRvSIyj4CksV8BjNi3sJtBsesoodqnm3zfg9qGa8L0UHU3SJInwhcHf2OEWPvWiQK46fA3pMIQ9l+rppTZ8ZBrBetT3Umsp6Bk1AF0y9OqhUldvxYI5vemVhVREPoGyXO+S7KERXCqHU/G1F2XR7BErbuSsjJariMh709JTBpRtHon7hnVanvG8cmZgDuztRiNUmozL07pXjiKn7H0AhImv69fwqyNirbDdkZJYqdPiPFRAklJo0lAL+zCccHprB7VJoKQzSI5Z21ooz0YMkEOqioPRQtRU3Mv894OT/7y3lQKbhDACBjZLYVbKYGvEKJ2jzIr14pat05YUmZb2oPSowRJ1/DcFhaV0eCQi0VVsC4Z3ZRyO3R188C3n1s7iu3m+1AEqBMJMRsXf6Eu3g3djCSPzuQ6QEFmBCVeSeQ+hqzUU9xtfh11E9RZOZF44488qmTKyQ3ZuFww61nN1Rip9j1fDD7FNbmJ+YV8w/N/Rlg5nNJVd8pDYwDVDf5r0Xxh5IR3RlZI3ZdBlmVfl7ErTkxY1VpdRCx4u2T2fZEPEE393q91sAB67SGkzQinS6uyYEYalRDoGMSzsBnaEDqJ8quj4ieZHJLy4qbvzbB0DHskX0SyE9OqIgdE3BkwEOhRdscOyS9HldY9MBzE="
  api_key: # e2f3
    secure: "AnmxZSel6VyLt+ElCMvqj7YwGB5MFFXNc1en6Bv5n5qgxXiLIS3CXdCeVVQf1RBtNnejlD+LHkzPV4NIRsBrTUJrE5exSU7waeRZ7lIb9/gn6cMAi6+HDO7B2dqaPZlxTWD/MHhS84tjORsCws4skMIrQPyEZ2wrKFl8bPn0mvT43WxKr9cyOBGNvd+Eh3BuDpD/fBjnuzr/waOS9eCX9uNqG+cUNa/8LMgpCiBFfeTQpTBUueTWQyY7vIUbH9vUzELxRPhm8gF984oTEHGjl2kGUwsUOnXDz4v0B0LWrvCqVBalB5K/lBrsiOoiVeXV0akCv0cEC5DzQMVpleM9KK0OGLfYQubREEJQwFF1wuYQzD6b4x3K7m/K1JzSASCxjo0XEpGFaRf/tdjR2XJnvsE1aAdIFx4XQprFNqqUk/U01Ec3ONw8Trz2It4wBunnGaXMsq9R5csga8l1HjxfhQM8njQheqU8MLLGgskdMQC6ucWCJlNFkJAjrPY+inFVnoejm/TqfijTZW9ak6KazPuhW0LyGtdzIRIhTcF6HbyqHGTkcCu2AYKNEKuP1CO5YVxOL5l3rF1T/9Gyn63vwPdw9S8tfBkTbSfuP1jxkgCwquAl5Iw4G9KUI3xMZYsHYWsqjrGDUZpevCoQEV5yinC/ppT05qRwtbhzHwzjlSk="
  on:
    tags: true
    node: lts/*
